### GET /setores
GET http://localhost:3333/setores

### POST /setores
POST http://localhost:3333/setores
content-type: application/json

{
    "nome":"Desenvolvimento WEB"
}

### GET /setores/:id
GET http://localhost:3333/setores/2

### PUT /setores/:id
PUT http://localhost:3333/setores/2
content-type: application/json

{
    "nome":"WEB Developer"
}

### DELETE /setores/:id
DELETE http://localhost:3333/setores/1

### ROTA DE TAREFAS

### GET /tarefas
GET http://localhost:3333/tarefas

### POST /tarefas
POST http://localhost:3333/tarefas
content-type: application/json

{
    "tarefa": "ensinar MODELS",
    "descricao": "Kahoot",
    "setor_id": 2
}

### GET /tarefas/:id
GET http://localhost:3333/tarefas/daeb8a38-5531-46a6-b5ef-64a53019849d

### PUT /tarefas/:id
PUT http://localhost:3333/tarefas/daeb8a38-5531-46a6-b5ef-64a53019849d
content-type: application/json

{
    "setor_id": 2,
    "situacao": "concluido"
}

### DELETE /tarefas/:id
DELETE http://localhost:3333/tarefas/c5f4b75e-631f-46a0-8b96-2f382944f253/1

### ---- ROTAS EXTRAS
GET http://localhost:3333/tarefas/situacao/concluido

###
GET http://localhost:3333/setores/2/tarefas